all:
  children:
    dwm:
      hosts:
        172.16.0.2:
      vars:
        ansible_user: alex 
        dwm_version: 6.5
        timezone: Australia/Sydney
        content_creation: true 
