---
- name: Create a SSH key for "{{ ansible_user }}" 
  ansible.builtin.user:
    name: "{{ ansible_user }}" 
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Create root code directory 
  ansible.builtin.file:
    path: /root/code 
    state: directory
    mode: '0700'
    owner: root 
    group: root 

- name: Create AppImage directory
  ansible.builtin.file:
    path: /opt/AppImage/ 
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Setup custom path and alias files
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/{{ item }}"
    dest: "/home/{{ ansible_user }}/.config/"
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - custom_path.sh
    - custom_alias.sh

- name: Ensure custom alias is added
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/{{ item.file }}" 
    line: "{{ item.line }}"
    state: present
    create: yes
  loop:
    - {file: ".profile", line: ". ~/.config/custom_alias.sh"}
    - {file: ".bashrc", line: ". ~/.config/custom_alias.sh"}
    - {file: ".profile", line: ". ~/.config/custom_path.sh"}
    - {file: ".bashrc", line: ". ~/.config/custom_path.sh"}
    - {file: ".profile", line: "feh --bg-scale https://w.wallhaven.cc/full/dp/wallhaven-dp3plm.jpg"}
    - {file: ".profile", line: "systemctl --user start dwm_status"}

- name: Clearing dmenu cache
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.cache/dmenu_run"
    state: absent

- name: Setup custom services 
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - {file: "dwm_status.service", dest: "/home/{{ ansible_user }}/.config/systemd/user/"}
    - {file: "status.sh", dest: "/home/{{ ansible_user }}/code/dwm_status/"}
    - {file: "daily_btrfs_snapshot.sh", dest: "/root/code/"}
    - {file: "btrfs_snapshot.service", dest: "/etc/systemd/system/"}
    - {file: "btrfs_snapshot.timer", dest: "/etc/systemd/system/"}
    - {file: "btrfs_snapshot@.service", dest: "/etc/systemd/system/"}
    - {file: "6_hour_snapshot.timer", dest: "/etc/systemd/system/"}

- name: Enable btrfs snapshots
  shell: "systemctl enable --now {{ item }}"
  loop:
    - btrfs_snapshot.timer
    - 6_hour_snapshot.timer 

- name: Enable status service 
  shell: "{{ item }}"
  become: no
  loop:
    - "systemctl --user enable dwm_status.service"
    - "systemctl --user daemon-reload"
    - "systemctl --user start dwm_status.service"

- name: Download Obsidian
  ansible.builtin.get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/Obsidian-1.6.7.AppImage
    dest: /opt/AppImage/
    mode: '0555'

- name: Download content creation AppImages 
  ansible.builtin.get_url:
    url: "{{ item }}" 
    dest: /opt/AppImage/
    mode: '0555'
  when: content_creation is defined and content_creation | bool
  loop:
    - https://github.com/audacity/audacity/releases/download/Audacity-3.7.1/audacity-linux-3.7.1-x64-22.04.AppImage
    - https://download.kde.org/stable/kdenlive/24.12/linux/kdenlive-24.12.2-x86_64.AppImage 

- name: Download and extract nvim
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.tar.gz 
    dest: /opt
    remote_src: yes
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Add nvim to $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/00-nvim.sh
    content: 'PATH=$PATH:/opt/nvim-linux-x86_64/bin:/opt/AppImage'

- name: Clone NvChad to ~/.config
  ansible.builtin.git: 
    repo: 'https://github.com/NvChad/starter'
    dest: "/home/{{ ansible_user }}/.config/nvim"
  become_user: "{{ ansible_user }}"

- name: Install user apps
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gimp
    - scrot
    - feh
    - alsa-utils
    - tmux

- name: Install content creation packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  when: content_creation is defined and content_creation | bool
  loop:
    - obs-studio
