---
- name: Create a SSH key for alex 
  ansible.builtin.user:
    name: alex 
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Download and extract nvim
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
    mode: '0700'
    owner: alex
    group: alex

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/AppImage/ 
    state: directory
    mode: '0700'
    owner: alex
    group: alex

- name: Download Obsidian
  ansible.builtin.get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/Obsidian-1.6.7.AppImage
    dest: /opt/AppImage/
    mode: '0555'

- name: Add nvim to $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/00-nvim.sh
    content: 'PATH=$PATH:/opt/nvim-linux64/bin:/opt/AppImage'

- name: set nvim config
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/templates/nvim"
    dest: /home/alex/.config/

- name: Setup DWM status user service 
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/templates/{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: '0700'
    owner: alex
    group: alex
  loop:
    - {file: "dwm_status.service", dest: "/home/alex/.config/systemd/user/"}
    - {file: "status.sh", dest: "/home/alex/code/dwm_status/"}

- name: Enable status service 
  shell: "systemctl --user start dwm_status.service"
  become: no

