---
- name: Manually run dpkg configure 
  shell: "dpkg --configure -a"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install DWM dependancies
  ansible.builtin.package:
    name: "{{ dwm_dependant_packages }}"
    state: present

- name: Remove GNOME desktop environment packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - gnome-shell
    - gnome-control-center
    - gnome-settings-daemon
    - gnome-tweaks
    - gnome-terminal
    - gnome-backgrounds
    - gnome-themes-extra
 

- name: Remove KDE Plasma desktop environment packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - plasma-desktop
    - kde-plasma-desktop
    - plasma-workspace
    - konsole
    - dolphin
    - kdeconnect
 
- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes

- name: Download DWM scource
  ansible.builtin.unarchive:
      src: "http://dl.suckless.org/dwm/dwm-{{ dwm_version }}.tar.gz"
      dest: /usr/local/src
      remote_src: yes

- name: Give insecure permissions to an existing file
  ansible.builtin.file:
    path: /usr/local/src
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes

- name: Run 'install' target as root
  make:
    chdir: "/usr/local/src/dwm-{{ dwm_version }}"
    target: install

- name: Install DWM (temp)
  ansible.builtin.package:
    name: dwm
    state: present

- name: backup dwm.desktop
  ansible.builtin.copy:
    src: /usr/share/xsessions/dwm.desktop
    dest: /usr/share/xsessions/dwm.desktop.bak
    remote_src: yes

- name: Remove DWM (temp)
  ansible.builtin.package:
    name: dwm
    state: absent

- name: backup dwm.desktop
  ansible.builtin.copy:
    src: /usr/share/xsessions/dwm.desktop.bak
    dest: /usr/share/xsessions/dwm.desktop
    remote_src: yes

- name: Set sddm as the defualt manager 
  ansible.builtin.copy:
    dest: /etc/X11/default-display-manager 
    content: "/usr/bin/sddm"
    mode: '0644'

- name: Reconfigure dpkg with special sauce
  shell: |
    export DEBIAN_FRONTEND=noninteractive
    dpkg-reconfigure sddm

- name: Set SDDM configure
  copy:
    dest: /etc/sddm.conf
    content: | 
      [General]
      DisplayServer=x11
      [Theme]
      Current=maldives
