- hosts: dwm
  become: yes
  tasks:

  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
      - "deb http://archive.ubuntu.com/ubuntu/ focal main restricted"
      - "deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted"
      - "deb http://archive.ubuntu.com/ubuntu/ focal universe"
      - "deb http://archive.ubuntu.com/ubuntu/ focal-updates universe"
      - "deb http://archive.ubuntu.com/ubuntu/ focal multiverse"
      - "deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse"
      - "deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security main restricted"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security universe"
      - "deb http://security.ubuntu.com/ubuntu/ focal-security multiverse"

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Install TigerVNC server and DWM dependancies
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - tigervnc-standalone-server 
      - tigervnc-xorg-extension 
      - tigervnc-viewer
      - build-essential 
      - libx11-dev 
      - libxinerama-dev 
      - sharutils 
      - suckless-tools 
      - libxft-dev 
      - stterm 
      - gcc

  - name: Download DWM scource
    ansible.builtin.unarchive:
        src: http://dl.suckless.org/dwm/dwm-6.2.tar.gz
        dest: /usr/local/src
        remote_src: yes

  - name: Give insecure permissions to an existing file
    ansible.builtin.file:
      path: /usr/local/src
      owner: ubuntu
      group: ubuntu
      state: directory
      recurse: yes

  - name: Run 'install' target as root
    make:
      chdir: /usr/local/src/dwm-6.2
      target: install

  - name: Install DWM (temp)
    ansible.builtin.package:
      name: dwm
      state: present

  - name: backup dwm.desktop
    ansible.builtin.copy:
      src: /usr/share/xsessions/dwm.desktop
      dest: /usr/share/xsessions/dwm.desktop.bak
      remote_src: yes

  - name: Install DWM (temp)
    ansible.builtin.package:
      name: dwm
      state: absent

- hosts: dwm
  tasks:

  - name: Start VNC with DWM
    ansible.builtin.cron:
      name: "Start VNC with DWM"
      special_time: reboot
      job: "/usr/bin/tigervncserver -xstartup /usr/local/bin/dwm"

  - name: Make VNC folder
    ansible.builtin.file:
      path: /home/ubuntu/.vnc
      owner: ubuntu
      group: ubuntu
      state: directory

  - name: Make VNC folder
    shell: "printf 'ubuntu\nubuntu\nn' | /usr/bin/tigervncserver -xstartup /usr/local/bin/dwm"

  # - name: Set config
  #   synchronize:
  #     src: "{{ playbook_dir }}/passwd"
  #     dest: /home/ubuntu/.vnc

  # - name: set VNC password
  #   shell: "echo ubuntu | vncpasswd -f > /home/ubuntu/.vnc/passwd"

- hosts: dwm
  become: yes
  tasks:

  - name: reboot
    ansible.builtin.reboot:

